### ISSUE TITLE
core-list-dart is broken

### ISSUE THREAD

**Issue by eugens-github** [dart-lang/polymer-dart#13]
Hello,

something like this worken with polymer 0.15.1+5 but with 0.15.5 the list won't render, without any warnings or errors:

```html
...
      <core-list-dart data="{{data}}" height="80">
          <template>
              <div class="{{ {selected: selected} }}" style="height: 80px">
                  List row: {{index}}, User data from model: {{model.name}}
                  <input type="checkbox" checked="{{model.checked}}">
              </div>
          </template>
      </core-list-dart>
...
```
```dart
...
@observable var data;
...
data = toObservable([
        new Person('Bob', true),
        new Person('Tim', false),
        new Person('Bill', true)
    ]);
...
class Person extends Observable {
  @observable String name;
  @observable bool checked;
  Person(this.name, this.checked);
}
```

**Comment by jakemac53** [comment]
Can you confirm that your core-list-dart has a intrinsic height on it? I think that this is probably not related to a polymer version upgrade but actually a core-elements version upgrade. `core-list-dart` used to not require an intrinsic height but now it does. This can usually be fixed by simply adding the `fit` attribute.

**Comment by eugens-github** [comment]
Yes, i used the 'height' attribute but now, as you mentioned, i have to use 'fit' and wrap it to a <div relative>. So the 'height' attribute will be ignored. Maybe you are right and the problem is core-element related. My core_element upgrade was 0.4.0+6 to 0.6.0+4.

**Comment by jakemac53** [comment]
core_elements 0.5.0 is when the changes happened to core-list-dart, so that is definitely why you started seeing the issue.

Regarding the `height` attribute, that does not actually affect the height of the core-list-dart element itself, but is instead just a hint to the core-list-dart about the average height it should expect each individual list item to be. This is used in combination with a few other things to calculate how many items it should render at a time.

**Comment by Kleak** [comment]
I have try to put an height and fit but nothing show up my list of item the only things that show up my list is to add a caractere between core-list-dart and my first template like this :

```dart
<core-list-dart id="list" data="{{ data }}">

  <!--  Here you have to put a letter in order to have your core-list rendered  -->
  e
  <!--  -->

  <template>
    <div class="row {{ {selected: selected} }}">
      List row: {{index}}, User data from model: {{model.name}}
    </div>
  </template>

</core-list-dart>
```

**Comment by jakemac53** [comment]
So if you inspect your core-list-dart element I think you will see that it has zero height (without the extra character). The `fit` layout attribute only works if one of its parents is fixed size and position relative, per https://www.polymer-project.org/0.5/docs/polymer/layout-attrs.html#general-purpose-attributes. 

The reason adding the character makes it sort of work is it makes sure there is a non-zero height on the element initially.

**Comment by Kleak** [comment]
ok, so why when i add the height attributes nothing appear?

**Comment by DanielJoyce** [comment]
Wrapped in relative div with explicit height, core-list-data not displaying anything.
<div relative style="height: 200px">
  <core-list-dart data="{{data}}" fit>
    <template>...</template>
  <fit>
</div>

I can see data coming in, but core-list-dart refuses to display it AT ALL.

**Comment by jakemac53** [comment]
If you open up the chrome inspector, does your core-list-dart element have a non-zero height? Css is finicky, so just the above styles alone don't necessarily guarantee that it does (something else on the page could be overriding it).
