### ISSUE TITLE
Inlined documents expose id's which can cause conflicts

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer-dart#50]
This gets really bad with icon sets, https://github.com/Polymer/core-icons/blob/master/core-icons.html for instance exposes a ton of elements with really common ids. These will get picked up by document.getElementById and querySelector calls :(.

**Comment by jakemac53** [comment]
One possible solution here is to inline these files into a separate html file, and then add an html import to that. This would only add one request and would solve all of these issues, as well as getting rid of the hidden div hack.

**Comment by sigmundch** [comment]
That's an interesting idea. I see an interesting tradeoff here. The good parts is what you mentioned above, but the downsides are that:

* the new approach would incur in a second request before an app is initialized
* with the old approach there is no dependency on HTML imports at deploy time, so potentially a developer using HTML imports and none of the other polyfills, could ship his app without any .js polyfills

I personally, and possibly some of our users, would prefer the old approach because of the first downside above.

**Comment by jakemac53** [comment]
Ya, I definitely agree the additional request isn't ideal, but I don't have a better solution yet :(

**Comment by jakemac53** [comment]
I am going to close this as not planned, its definitely still a potential issue but I don't know of an acceptable resolution at this time and it doesn't seem to be causing to many issues.
