### ISSUE TITLE
[0.17] align syntax with polymer-typescript

### ISSUE THREAD

**Issue by nippur72** [dart-lang/polymer-dart#518]
I propose to align the syntax of the new PolymerDart 0.17 with its TypeScript counterpart, which I'm managing at [nippur72/PolymerTS](https://github.com/nippur72/PolymerTS) (it's an unofficial project).

If we agree on a common syntax, it will be easier for users to switch between the two languages and/or reuse elements.

[nippur72/PolymerTS](https://github.com/nippur72/PolymerTS) currently supports the following @decorators:

- `@component` (equivalent to `@PolymerRegister`)
- `@property` (same as PolymerDart)
- `@observe` (same as PolymerDart but makes distinction between single and multiple props)
- `@computed` (can decorate a function and define a computed prop of the same name)
- `@listener` (equivalent to `@listen`)
- `@template` and `@style` for creating elements imperatively (no .html)

In PolymerTS there is no `@eventhandler`, but there is `@behaviour` for handling behaviours.

**Comment by jakemac53** [comment]
One comment about @computed, I am not sure on how the semantics work in PolymerTS, but in dart when you create/select an element the type you get is going to be the actual class that you are writing. Because of that I need to keep computed properties as annotations on an actual property, not a method (can't dynamically add properties in dart, and it would be a naming conflict).

For @component vs @PolymerRegister, I am a bit torn. I would like to not have naming conflicts with angular, and I would like it to be more descriptive. Ideally it would actually be @Polymer to match the `Polymer()` function, but we already have a separate class by that name. It also can't be @PolymerElement because we have a class by that name too :(. I think it would be good to get some additional feedback, I do agree that @PolymerRegister doesn't quite feel right. Maybe a naming conflict with angular is actually ok.

For @template and @style... on the polymer TS side what are you doing for the implementation of these? Do you dynamically create dom-module tags, or are you doing something else? I have actually been advocating lightly for something like this for a while, but I have not been able to convince others as of yet. We also already have @HtmlImport, which can effectively wrap up both of these (you can put a dom-module inside your html file). For polymer it might actually make more sense to have an @DomModule, with template and style as named arguments (does TS have named args)?

For @listener, I am not opposed to changing this, but if we did then I think we should also change @observe to @observer. I would like these two to be consistent.

@eventHandler you can ignore, it should eventually go away. It is just a way of annotating methods so they are available to the static reflection system post-transformation.

**Comment by nippur72** [comment]
Regarding `@computed`, yes it annotates a function and also does a dirty hack to have a property of the same name of annotated function. But the result is nice because you can do things like this:
```TypeScript
@computed 
function fullname(fistName,lastName) {
   return fistName +" "+lastName;
}
```
Note that here `@computed` also scans for parameter names avoiding to write 
```TypeScript
@computed("fistName,lastName")
```
Don't know if that is possible in Dart (with mirrors perhaps?), in JavaScript I do that the same way angular1 does dependency injection, by first `function.toString()` and then scanning for `(`, `)` etc..

Regarding `@component` vs `@PolymerRegister`, what about `@element` ? It seems to me the most meaningful one. Other choices would be `@tag` or perhaps the old `@customTag`. 

As for `@template` and `@style`, yes they create a `<dom-module>` dynamically. Actually I don't know how much useful is this option, but it seems important to me to have the possibility to define an element using one single file only. In plain JavaScript that is possible by having a .html file and `<script>`, but in TypeScript and Dart you always need two files.

Maybe the two decorators could be packed into one (`@domModule`); btw TS doesn't have named parameters (yet), but that is not a big issue (`domModule(template,style)` is still fine).

As for `@listener` vs `@listen` don't mind, I was about to rename it :-)

There will still be a `@whenPolymerReady` ?

**Comment by jakemac53** [comment]
> Don't know if that is possible in Dart (with mirrors perhaps?), in JavaScript I do that the same way angular1 does dependency injection, by first function.toString() and then scanning for (, ) etc..

The main issue is we can't create a property with the same name as the function, or even add a property dynamically at all. We could omit the arguments from the method string and use reflection to fill those in, but that doesn't allow you to re-use the same method for two different, computed properties, and forces names on the actual method arguments that maybe don't actually make the most sense.

> Regarding `@component` vs `@PolymerRegister`, what about `@element` ? It seems to me the most meaningful one. Other choices would be `@tag` or perhaps the old `@customTag`.

Unfortunately `dart:html` defines an `Element` class, so that one isn't really an option. I was never a fan of `@CustomTag` in the past... its to close to `@CustomElement` (a vanilla custom element). Still not sure what the best thing is here.... `@Component` might end up being a good solution.

> As for `@template` and `@style`, yes they create a <dom-module> dynamically. Actually I don't know how much useful is this option, but it seems important to me to have the possibility to define an element using one single file only. In plain JavaScript that is possible by having a .html file and <script>, but in TypeScript and Dart you always need two files.

> Maybe the two decorators could be packed into one (@domModule); btw TS doesn't have named parameters (yet), but that is not a big issue (domModule(template,style) is still fine).

I do like the idea of making them into one, called `@DomModule`. @sigmundch what do you think about that? This would be pretty trivial to implement, although it would require the use of a NullSanitizer for setting innerHtml (in mirrors mode, we could inline these into the document in the transformer). I would use this myself actually for smaller elements.

> As for `@listener` vs `@listen` don't mind, I was about to rename it :-)

If you want to just rename to `@listen`, that sounds good.

> There will still be a @whenPolymerReady?

Yes, I just added https://github.com/dart-lang/polymer-dart/issues/519 to track this.

**Comment by kasperpeulen** [comment]
I was reading the polymer TodoMVC example @jakemac53, and this syntax seems a bit cumbersome:

```
  @Property(computed: 'getClassString(editing, item.completed)')
  String classString;

  @eventHandler
  String getClassString([_, __]) =>
      'view${editing ? ' editing' : ''}${item.completed ? ' completed' : ''}';
```

Would it be possible to have something like this ?

```
  @Property()
  String get classString => getClassString(editing, item.completed);
```

**Comment by jakemac53** [comment]
> Would it be possible to have something like this ?
>> @Property()
>> String get classString => getClassString(editing, item.completed);

This wouldn't have quite the same semantics. Computed bindings actually cache their values, they don't recompute each time they are read.

**Comment by jakemac53** [comment]
Actually though I should change that to be a computed binding in the example anyways.

**Comment by jakemac53** [comment]
Closing this as the current api for PolymerDart is unlikely to change
