### ISSUE TITLE
Polymer passing object='0' and target='null' to event handler on-keyup

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/polymer-dart#556]
I ported stagehand's polymer web sample to 0.17-0-dev-interop-reverse. The event handler for reverseText is called, but object = 0 and target = null.  Here's the [gist] (https://gist.github.com/ErikGrimes/c18ebe9b4236f4dd6cb4).

**Comment by jakemac53** [comment]
Actually, this is working as intended it looks like. The issue is the 3rd argument (target) is not supported at all. However the way we [invoke this function today](https://github.com/dart-lang/polymer-dart/blob/0.17-0-dev-interop-reverse/lib/src/common/js_proxy.dart#L90) using smoke we use the `adjust: true` option. This adds nulls for any extra arguments. The detail of `0` seems to be consistent with any key listeners on input fields. If you want the character code you need to read `event.charCode`.

We are currently working on migrating to the `reflectable` package, and will [no longer be adjusting arguments like this](https://github.com/dart-lang/polymer-dart/blob/behaviors/lib/src/common/js_proxy.dart#L99) (which is error prone anyways). You would get a runtime warning that a method with 3 expected arguments was called with only 2.
