### ISSUE TITLE
method not found 'prefix7.JsoNativeFieldWrapper

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#584]
I get this error 

> Exception: No top-level getter 'prefix7.JsoNativeFieldWrapper' declared.
>
> NoSuchMethodError: method not found: 'prefix7.JsoNativeFieldWrapper'
Receiver: top-level
Arguments: [...]index.dart:34 init:_data@991803039index.dart:34 get:_data@991803039index.dart:43 _initializeReflectable@991803039index.dart:30 mainindex.bootstrap.dart:5 mainindex.bootstrap.initialize.dart:43 main

in this example https://github.com/bwu-dart-contributing/polymer-dart-patterns/tree/0.17.0/web/layout_attributes/nesting_flex_layouts

and also in https://github.com/bwu-dart-playground/polymer1/tree/master/iron_icon_transition/web
which was already working yesterday.

**Comment by jakemac53** [comment]
Just to confirm, are you using reflectable version 0.2.0?

**Comment by zoechi** [comment]
I updated the reflectable version to 0.2.0 as suggested but I still get the same error.

**Comment by zoechi** [comment]
When I use 
```yaml
  polymer:
    git:
      url: git@github.com:dart-lang/polymer-dart.git
      ref: aea190df60e6c9d20078d89919443dea8e1b1997
```
the examples are working fine again, also with reflectable 0.2.0 .

**Comment by jakemac53** [comment]
Hmm, I can't reproduce this error unfortunately :(

**Comment by zoechi** [comment]
Weird. I had this is in most examples. I did a screen-sharing with @damondouglas to coordinate our work on polymer-dart-patterns and he run into the same issue. I'll try again tomorrow.

**Comment by jakemac53** [comment]
I remember I had this issue a long time ago, but when I updated reflectable it stopped happening. Maybe there was something more subtle actually going on though?

**Comment by zoechi** [comment]
I updated to the latest of polymer-dart behaviors and now all my examples are working.

**Comment by zoechi** [comment]
In my personal Polymer examples project I still run into this. I use the `pubspec.lock` from `polymer-dart-patterns` with `pub get` and compared everything else but I wasn't able to make it work here.

**Comment by zoechi** [comment]
I copied the files from one of the examples of `polymer-dart-patterns` with the `pubspec.yaml` file to a new project, but there I also get the exception 
> No top-level getter 'prefix9.JsoNativeFieldWrapper' declared.

**Comment by zoechi** [comment]
I investigated a bit more. A weird thing is that the `index.dart` generated for the new project (where I get the error) has additional imports like
```dart
import 'dart:collection' as prefix14;
import 'package:polymer_interop/src/polymer_base.dart' as prefix11;
```
which are not in the generated `index.dart` of the same example when run from the `polymer-dart-patterns` project (where I don't get the error).

**Comment by zoechi** [comment]
https://github.com/bwu-dart-playground/jsonativefieldwrapper_error/tree/master/web/forms
contains both files 
`index_generated_error.dart` generated when running the example from the `jsonnativefieldwrapper_error` project and `index_generated_working.dart` generated from the same example when run from the `polymer-dart-patterns` project. 
I just copied the files and removed redundant entry-point lines and fixed the path of the remaining entry-points.

`index_generated_error.dart` also contains a lot of `JsoNativeFieldWrapper` while  `index_generated_working.dart` doesn't contain it at all.

**Comment by jakemac53** [comment]
cc @eernstg @sigurdm

**Comment by eernstg** [comment]
Hello Jacob and Günter,

I just got this 'heads up' marker, noting that the issue hasn't disappeared
in thin air.  ;-)

I fetched '
https://github.com/bwu-dart-playground/jsonativefieldwrapper_error.git',
did 'pub get' and 'pub build --mode=debug', which works fine. It produces a
file 'index.dart', and it behaves as follows:

---------------------------------------------------------------------------------------------
...$ dartanalyzer --package-root=build/web/packages
build/web/forms/index.dart
Analyzing [build/web/forms/index.dart]...
No issues found
...$
---------------------------------------------------------------------------------------------

'index.dart' is not identical to 'index_generated_working.dart' (not the
same imports, not the same `data`) nor 'index_generated_error.dart'
(different `data`), so I'm not able to obtain any of those two files by
running `pub build ..`.

Does the same sequence of actions produce the errors for you? Maybe you are
running a different version of various tools? My `pub` and `dartanalyzer`
both report the version as 1.12.0.


On Tue, Sep 22, 2015 at 3:40 PM, Jacob MacDonald <notifications@github.com>
wrote:

> cc @eernstg <https://github.com/eernstg> @sigurdm
> <https://github.com/sigurdm>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/polymer-dart/issues/584#issuecomment-142292279>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by zoechi** [comment]
I'm using 
> Dart VM version: 1.13.0-edge.232a9d687e9abf3a315e9b5c980334c2313f94a8 (Tue Sep 22 03:33:53 2015) on "linux_x64"

I generated the file by opening it from the `http://localhost:...` url Dartium uses to fetch the file.
The two included `index_generated_xxx.dart` files are already different, even though they are generated from the same source (only copied from one project to a new project but everything the same (like pubspec.lock) except the paths are a bit different).

I don't get analyzer errors, I get the errors in the browser console when I load the `index.html` file from `pub serve` in Dartium.
When I open the file `index_generated_error.dart` in WebStorm code naviation from `prefixX.JsoNativeFieldWrapper` to the declaration works fine.

I can still make the project work by switching the dependency on polymer to a specific commit
```yaml
  polymer:
    git:
      url: git@github.com:dart-lang/polymer-dart.git
      ref: aea190df60e6c9d20078d89919443dea8e1b1997
```
I tried several commits before and after this one, but only this one worked.

In the https://github.com/bwu-dart-contributing/polymer-dart-patterns/tree/0.17.0 project all examples started working today also with the latest commit in the `behavior` branch, but https://github.com/bwu-dart-playground/jsonativefieldwrapper_error and https://github.com/bwu-dart-playground/polymer1 only work with the specific commit of the Polymer dependency.

**Comment by zoechi** [comment]
I just deleted the `.pub` directory in the https://github.com/bwu-dart-contributing/polymer-dart-patterns/tree/0.17.0 project  (which was working with the recent Polymer version since today) and run `pub upgrade` and now it is broken as well again.

**Comment by eernstg** [comment]
Hello again Günter,

I fetched a fresh copy using `git clone '
https://github.com/bwu-dart-contributing/polymer-dart-patterns'`
<https://github.com/bwu-dart-contributing/polymer-dart-patterns'>, then did
`git co 0.17.0` in 'polymer-dart-patterns', then started `dartium`
(1.12.1.0), did `pub get`, `pub serve`, and loaded '
http://localhost:8080/layout_attributes/nesting_flex_layouts/index.html'
into dartium and saw a layout with several rectanges. All OK, no errors.
This means that I don't see the breakage you mentioned most recently.

Then I did `git clone '
https://github.com/bwu-dart-playground/jsonativefieldwrapper_error'`,
checked that it is identical to the one I already had fetched yesterday,
did `pub get`, `pub serve`, loaded 'http://localhost:8080/forms/index.html'
in dartium, tried the check box (which changes the label to 'Uncheck' and
then 'Check', indicating the effect of the next click.

The only output I get from `pub serve` is the following:

------------------------------------------------------------
...$ pub serve
Loading source assets...
Loading web_components and reflectable transformers...
Serving polymer_dart_samples web on http://localhost:8080
Build completed successfully
[web] GET Served 66 assets.
[web] GET /favicon.ico → Could not find asset
polymer_dart_samples|web/favicon.ico.
...
------------------------------------------------------------

From `dartium` I get some noise, but it doesn't seem to be relevant:

------------------------------------------------------------
...$ dartium
[10483:10483:0923/141546:ERROR:browser_main_loop.cc(163)] Running without
the SUID sandbox! See
https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for
more information on developing with the sandbox on.
[10527:10527:0923/141547:ERROR:renderer_main.cc(207)] Running without
renderer sandbox
Observatory listening on http://127.0.0.1:59296
[10483:10483:0923/141613:ERROR:browser_main_loop.cc(209)] Gdk:
gdk_window_set_user_time called on non-toplevel

[10483:10483:0923/141613:ERROR:browser_main_loop.cc(209)] Gdk:
gdk_window_set_user_time called on non-toplevel

[10483:10483:0923/141613:ERROR:browser_main_loop.cc(209)] Gdk:
gdk_window_set_user_time called on non-toplevel
...
------------------------------------------------------------

Does that sound like an exact replay of what you need to do in order to see
the `JsoNativeFieldWrapper` problem, or am I doing something differently?
I'm using tools version 1.12.0 which ought to be a reasonable choice
(switching to 1.12.1 now), but I could of course try out others, including
bleeding edge.



On Tue, Sep 22, 2015 at 8:28 PM, Günter Zöchbauer <notifications@github.com>
wrote:

> I just deleted the .pub directory in the
> https://github.com/bwu-dart-contributing/polymer-dart-patterns/tree/0.17.0
> project (which was working with the recent Polymer version since today) and
> run pub upgrade and now it is broken as well again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/polymer-dart/issues/584#issuecomment-142372991>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by zoechi** [comment]
@eernstg 
Erik,
thanks for taking a look!
It's just too weird, I have this in all my projects (3).
I have no idea how to further isolate the source of the issue.
I guess I'll wait until @jakemac53 provides a newer Polymer version and then I'll try again.

**Comment by eernstg** [comment]
Sigurd actually saw the problem at one point later this afternoon, but I tried to do _exactly_ what he had done and I still couldn't reproduce the problem (Sigurd couldn't either, I believe). We'll await further input.

**Comment by zoechi** [comment]
I purged my `~/.pub-cache` directory and tried again with the latest version of the behaviors branch. I get the same error. 
I also can't switch back to the working commit (mentioned above) because with this commit id I now just get a Git error from `pub upgrade`.
What OS and Dart version did you try to reproduce?

**Comment by sigurdm** [comment]
I believe I tracked this one down.
class JsoNativeFieldWrapper was added recently to the SDK html lib.
So it is probable that you run pub with a bleeding edge checkout, and your
dartium is somewhat behind, and therefore doesn't know about
JsoNativeFieldWrapper.

I made a checkout of the sdk repo at `7ef93ef` (The commit before
JsoNativeFieldWrapper was introduced), did a `gclient sync; gclient
runhooks; ./tools/build.py -mrelease` and restarted pub serve, and it
worked.

Not sure what the best way to solve the problem in general is, except
recommending to always use corresponding versions of pub and dartium.

**Comment by zoechi** [comment]
Great. Thanks for the update. I'll investigate whether my Dartium is out of sync and how to prevent that.

**Comment by zoechi** [comment]
I don't build myself (never got it working on my Debian system). I download from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/dartium/.
The files in the `dartium` directory seem not to be updated since 16. September. This is also the day my previously working Polymer-dart commit is from.

**Comment by sigurdm** [comment]
What sdk/pub are you using?

The problem is that there doesn't exist a Dartium that is new enough yet,
so you probably need to downgrade the sdk you are using.

On Fri, Sep 25, 2015 at 11:36 AM, Günter Zöchbauer <notifications@github.com

**Comment by zoechi** [comment]
I switched back to 
> Dart VM version: 1.13.0-edge.b0ca0789be616560c77315ecca290ebcb0735606 (Fri Sep 11 12:35:53 2015) on "linux_x64"
and now it's working. 
You made my day! :smiley:

**Comment by zoechi** [comment]
I guess I close it here. I created an issue in the SDK repo for the out-of-sync Dartium. We'll see what they respond over there.
I'm aware that there is bigger work going on in Dartium right now and that I'm on bleeding edge.
