### ISSUE TITLE
Reflecting on un-marked type 'JsObjectImpl'

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#600]
> Uncaught Unhandled exception:
Reflecting on un-marked type 'JsObjectImpl'
#0      _InstanceMirrorImpl._InstanceMirrorImpl (package:reflectable/src/reflectable_transformer_based.dart:147:9)
#1      ReflectableImpl.reflect (package:reflectable/src/reflectable_transformer_based.dart:1117:16)
#2      _setUpPropertyChanged.<anonymous closure> (package:polymer/init.dart:65:47)polydev/vendor/zone-microtask.js:123 runpolydev/vendor/zone-microtask.js:91 zoneBoundFnindex.html:5362 Polymer.Base._addFeature.fireindex.html:12594 Polymer.IronButtonStateImpl._userActivateindex.html:12579 Polymer.IronButtonStateImpl._tapHandlerindex.html:4345 handlerpolydev/vendor/zone-microtask.js:118 runpolydev/vendor/zone-microtask.js:91 zoneBoundFnindex.html:5362 Polymer.Base._addFeature.fireindex.html:4749 Gestures.fireindex.html:5022 Gestures.register.forwardindex.html:5003 Gestures.register.clickindex.html:4628 Gestures.handleNativepolydev/vendor/zone-microtask.js:118 runpolydev/vendor/zone-microtask.js:91 zoneBoundFn

I'm working on porting the iron_localstore demo
When I click the `<paper-checkbox checked="{{value.hasEars::change}}">` where `value` is initialized with `{'name': "Mickey", 'hasEars': true}`.

When I initialize `value` with `convertToJs({'name': "Mickey", 'hasEars': true})` it works fine.

When `value` is initialized with the unconverted Dart map, it gets persisted to localstorage like `{"name":"Mickey","hasEars":true,"__dartClass__":{}}` and causes the exception when it is restored.

I don't know if this is "as designed" or a bug.

**Comment by zoechi** [comment]
With `convertToJs` it only fails on another place. I can't get a map back from the value loaded from localstorage. Also `convertToDart` doesn't help.

**Comment by jakemac53** [comment]
Can you link to the full project?

**Comment by zoechi** [comment]
https://github.com/bwu-dart-contributing/polymer_elements/tree/demo2/demo/web/iron_localstorage

The transformer is quite slow, therefore I comment out all entry points but the one I'm currently working on in `pubspec.yaml` (but it's still quite slow but seems a bit faster)

**Comment by jakemac53** [comment]
Ya that is because the reflectable transformer currently uses an aggregate transformer, cc @eernstg @sigurdm.

**Comment by eernstg** [comment]
As far as I remember, the transformation speed went up by a factor of 5 when we switched from a plain `Transformer` to an `AggregateTransformer`, it was certainly a lot faster. It is true that we had to do that because we needed to perform a whole-program transformation. But note that a plain `Transformer` is just a thin wrapper for an `AggregateTransformer`, so you won't get any magic benefits from the plain one that the aggregate one can't deliver. I believe the speed-up we saw had to do with elimination of duplicate work (e.g., analyzing the same libraries several times).

That said, we certainly need to work carefully on the performance of the reflectable transformer. It's not quite obvious what it can be compared to, in order to determine whether it's slow compared to reasonable expectations, but any bottlenecks that we can discover and eliminate will of course be helpful no matter where it is in that spectrum. 

And thanks for the input, please give more information (as a reflectable issue ticket) if you have specific ideas about this topic!

**Comment by zoechi** [comment]
I'm wondering why this causes any notable impact at all. 
Shouldn't it just use mirrors during development?
My issue is with running in Dartium not with running `pub build`.

**Comment by eernstg** [comment]
Aha, so when you said `The transformer` you weren't referring to the reflectable transformer at all?

**Comment by sigurdm** [comment]
We currently don't have a way for the transformer to know if it is running for dartium (no need to transform) or for dart2js (need to transform). So currently to run with the mirror-based version you need to manually disable the transformer.
It would preferably work like the dart2js transformer, but I think that behavior is hardcoded into pub for that specific transformer. I would be happy to learn otherwise though.

**Comment by zoechi** [comment]
@eernstg I have two transformers configured (`web_components` and `reflectable`) and I assume one of them (or both) cause the slowdown. @jakemac53 referred to the reflectable transformer.

Currently I'm working on hello-world sized examples and I'm waiting up to a minute to get the page loaded into the browser. Frequently it takes forever which is usually just before `pub serve` crashes with OOM. 
While this is alpha or beta state I can live with it but in production its unusable.

**Comment by eernstg** [comment]
We're transforming about 44 entry points in about 15 seconds total (test_reflectable/test/*_test.dart). Each of those may be much smaller than what you are working with because your hello-world sized examples may import a large number of other libraries, but it sounds like you're hitting something else. You already commented on issue https://github.com/dart-lang/reflectable/issues/32, but do you think that this is unrelated?

**Comment by zoechi** [comment]
I can't tell if they are related. 
If the reflectable transformer has a lot of complicated work to to I can imagine this using a lot of memory and somehow leaking by the transfomer or pub or the combination. 
I don't know what the web_components transformers task is. Might be involved as well. I didn't use `reflectable` without `web_components` yet.

I'm still wondering why the transformer has to run at all. I think this should be fixed. As far as I understand the code should work fine in Dartium without the changes the transformer makes.
This breaks the entire development experience (develop-load-cycle). 
I'm curious what the response to the pub issue will be.

**Comment by eernstg** [comment]
OK, you're running `pub serve` which will presumably work like `pub build` except that it will perform the requested transformations whenever a file is fetched (from 'build/<some-path>') that has an older time stamp than one of the files that it depends on (usually, '<some-path>' except for the cases where a transformer outputs more assets than it receives as input, or uses different names for the output). So if dartium takes too long to show those pages it's probably because `pub serve` takes too long to deliver them, which may well be because it is running a transformation that takes too long.

The transformer is invoked by `pub` iff it is requested, that is, if it is listed in 'pubspec.yaml', subject to adjustments like `include` and `exclude`. The transformer itself cannot know whether it was called by `pub serve` or `pub build`, and it cannot know which program(s) are waiting for its output.

So if you don't want a certain transformation then you can omit the request for it in 'pubspec.yaml'. In particular, if you omit the reflectable transformer for your example programs (just don't list them as entry points) then you'll get the code using 'package:reflectable/reflectable.dart' in "pre-transformed mode", that is, using 'dart:mirrors'; dartium will then receive this code from the web server that `pub` sets up. It sounds like that might work for you?

**Comment by zoechi** [comment]
@sigurdm pointed out already in a previous comment that the transformer can't know. I created an issue in the pub repo dart-lang/pub#1338

If I remove the entry point I get
> /usr/local/apps/dart/dart-sdk/bin/pub serve web --port=38276
Loading source assets...
Loading reflectable, web_components and test/pub_serve transformers...
Info: No entry points, nothing to do..
Pub Serve terminated

If I also remove the `reflectable` transformer entry from `pubspec.yaml` I get
> Exception: Uncaught Error: Bad state: Reflectable has not been initialized. Did you forget to add the main file to the reflectable transformer's entry_points in pubspec.yaml?
Stack Trace:
#0      data (package:reflectable/src/reflectable_transformer_based.dart:116:5)
#1      data (package:reflectable/src/reflectable_transformer_based.dart:115:33)
#2      ReflectableImpl.reflectType (package:reflectable/src/reflectable_transformer_based.dart:1132:26)
#3      declarationsFor (package:polymer/src/common/declarations.dart:30:36)
#4      propertyDeclarationsFor (package:polymer/src/common/polymer_descriptor.dart:44:10)
#5      _buildPropertiesObject (package:polymer/src/common/polymer_descriptor.dart:52:22)
#6      createPolymerDescriptor (package:polymer/src/common/polymer_descriptor.dart:25:19)
#7      PolymerRegister.initialize (package:polymer/src/common/polymer_register.dart:19:36)
#8      loadInitializers.<anonymous closure>.<anonymous closure> (package:initialize/src/static_loader.dart:46:32)
#9      _runInitQueue (package:initialize/initialize.dart:35:24)
#10     _runInitQueue.<anonymous closure> (package:initialize/initialize.dart:38:26)
#11     _RootZone.runUnary (dart:async/zone.dart:1165)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#14     _Future._completeWithValue (dart:async/future_impl.dart:376)
#15     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#17     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#18     _ScheduleImmediateHelper._handleMutation (dart:html:42565)

This might be a Polymer.dart issue.

It also shouldn't be necessary to change `pubspec.yaml` between development and deployment (thus the pub issue mentioned above).

**Comment by sigurdm** [comment]
I think what we need for this could be a LazzyTransformer https://www.dartlang.org/tools/pub/transformers/lazy-transformer.html

**Comment by zoechi** [comment]
@sigurdm this might be worth a try. I still think during development it should just skip the transformer and use mirrors instead.

**Comment by eernstg** [comment]
Regarding 'If I also remove the reflectable transformer entry from pubspec.yaml': Ah, that's a problem. We run untransformed code as well as transformed code all the time, but we haven't tried avoid transformation of the code in the 'build' tree, we just run the untransformed code as given in the source tree (that is, we run 'test/my_test.dart' to get the untransformed behavior and 'build/test/my_test.dart' to get the transformed behavior).

In 'build' (with --package-root=build/..something..), the copy of 'reflectable.dart' that you get is slightly different:

-----------------------------------------------------------
...$ diff build/test/packages/reflectable/reflectable.dart ../reflectable/lib/reflectable.dart
14c14
< import 'src/reflectable_transformer_based.dart' as implementation;
---
> import 'src/reflectable_mirror_based.dart' as implementation;
-----------------------------------------------------------

In order to run untransformed code in 'build' you would need to avoid that change. We don't have a good way to enable you to turn it off.  Thinking about it. ;)

**Comment by sigurdm** [comment]
I completely agree - I just don't know a mechanism to allow the transformer to know if the environment is dart vm-like (mirrors allowed, we can save the transformation) or .dart2js (or sky)-like (mirrors should not be used, please transform).
We discussed using the --mode flag of pub (eg. you would write `pub serve mode=reflectable_untransformed`).
But that flag seems to have orthogonal meanings - What if you want to avoid transformation, and have --mode=debug at the same time?
Maybe @munificent has some ideas.

**Comment by zoechi** [comment]
Ok, lets wait for a response to the `pub` issue.

**Comment by jakemac53** [comment]
A bit late to the party here, but the way to avoid transformers and run in mirrors mode is to just avoid pub serve altogether. Run a simple local server of any kind any you will have instant refresh/etc. This comes up pretty often, and when polymer 1.0.0-rc.1 is released I am definitely going to encourage people to go that route. In my opinion pub serve should only be used for running tests of the post-transform output, and pub build should only be used for deployment. All other development should be done without them because the transformers just slow things down dramatically.

**Comment by jakemac53** [comment]
Also with regards to aggregate transformer vs normal transformer, the real issue here is not total time to transform all entry points together, but rather total time to transform a single entry point. You are typically only editing a single entry point at a time, but are forced to constantly re-transform all entry points on each file change.

Also with regards to speed the initial speedup was presumably related to not sharing a global `Resolvers` object in the simple transform. If you create a new one of those at the top of `apply` then yes things will be very slow, but if you create one per instance of the transformer then its still shared across all entry points that are ran in the same isolate, which is usually all of them.

**Comment by zoechi** [comment]
@jakemac53 don't you think `pub` should be fixed? `pub` is **the** development server for Dart.
When you want to use Polymer and Angular together, assuming Angular 2 is built like Angular 1 that it doesn't work without the transform step, you're out of luck.

**Comment by jakemac53** [comment]
Angular 2 does work without transformation ;)

**Comment by eernstg** [comment]
Aha, I thought that the `web_components` transformer had to run. If all transformers can be omitted then using the source directory should be fine, that's exactly what we are doing to get untransformed execution.

**Comment by jakemac53** [comment]
@zoechi Possibly pub could just have a flag which turns off transformers completely? You should be able to run and compile to JS any well-behaved dart app without any transformations, it just might not be fully optimized.

**Comment by zoechi** [comment]
@jakemac53 
Yes, I assumed that they won't do it again for Angular 2, but it's still a good example that such frameworks exist.

> Possibly pub could just have a flag which turns off transformers completely? You should be able to run and compile to JS any well-behaved dart app without any transformations, it just might not be fully optimized.

I don't think this is the solution (see above comment). Some transformers might be necessary in every case, some can be omitted with Dartium.
I think connecting it with `dart2js` would be the best solution. Either run the transformer always, or only when dart2js is run (default)
"fully optimized" shouldn't be relevant, IMHO reload time counts during development.

Should running without `pub serve` (with a plain web server) work already with Polymer?
Looks like I'm getting interested in https://youtrack.jetbrains.com/issue/WEB-14805 at last.

**Comment by jakemac53** [comment]
> I think connecting it with dart2js would be the best solution. Either run the transformer always, or only when dart2js is run (default)

The main issue with that is it means you can't debug the transformed output as easily. The user would probably need some way of forcing the transformers on in dartium still, as debugging the dart2js output is significantly more difficult.

**Comment by eernstg** [comment]
Sigurd and I discussed the incrementality issue earlier today, and it seems likely to me that pub needs help to track the relevant dependencies.

If pub serves 100 files from a build directory then they might have been created by running the transformer on 2 entry points in the context of 90 other files. Transformation of some files would be 1-to-1 (maybe 'web/my_picture.png' is identical to 'build/web/my_picture.png'), others would be similar to a rename ('web/index.dart' could be identical to 'build/web/index_reflectable_original_main.dart'), yet others would be  new (the reflectable transformer could generate 'build/web/index.dart' from scratch), and there could be arbitrary variants (delete file, merge files, ...).

I don't see how pub could receive a request for a given file from 'build/...' and then determine how that maps back to any specific set of input files, so it couldn't run transformations (other than "run all transformations") on demand.

So the only thing pub could do would be to keep track of the time stamps on files in the source directory tree, and then it could run transformations whenever anything changes there. But in order to avoid running all transformations it would have to know which dependencies there exist among the files in the source directory; for instance, if 'web/utils.dart' has been modified, do we have to re-transform entry point 1, or entry point 2, or both? How about 'web/my_picture.png'?

It would not work in general to assume Dart language rules when deciding how the dependency graph is structured; for instance, files in the source directory might contain dangling `part` directives that will be satisfied in the output because the corresponding part file will be generated.

To me it looks like incremental updates would have to rely on user-specified rules. In return, of course, transformations could be near-optimal, if anyone puts in the effort to specify good rules.

**Comment by jakemac53** [comment]
> Should running without pub serve (with a plain web server) work already with Polymer?

Yes that works today, its how I am doing all development.

**Comment by jakemac53** [comment]
> I don't see how pub could receive a request for a given file from 'build/...' and then determine how that maps back to any specific set of input files, so it couldn't run transformations (other than "run all transformations") on demand.

cc @munificent Bob could probably explain this better but basically it knows exactly which files any given output file depends on because you have to go through the barback apis to read any dependencies. So for any given call to `apply`, you might have any number of calls to `transform.readInputAsString` (or other apis) and also some calls to `transform.addOutput`. Any asset which is output will have a dependency on all files that were read as inputs. It doesn't have any specific knowledge about dart files or dart language rules at all, its much more general than that.

**Comment by zoechi** [comment]
> > I think connecting it with dart2js would be the best solution. Either run the transformer always, or only when dart2js is run (default)

> The main issue with that is it means you can't debug the transformed output as easily. The user would probably need some way of forcing the transformers on in dartium still, as debugging the dart2js output is significantly more difficult.

This scenario would be supported with my suggestion

My request is about a configuration to set one of these two modes for a transformer:
- apply the transfomer in any case 
  - to debug transformed output and 
  - for scenarios like in Angular.dart 1 apps that couldn't be run without the transfomer  
- apply the transfomer only with dart2js (to skip a transfomer with Dartium)

> Yes that works today, its how I am doing all development.

good to know

**Comment by jakemac53** [comment]
Ah so it would be a pubspec level configuration in the users package, not something that is exposed to the transformer itself?

**Comment by eernstg** [comment]
Aha, very good! --- We don't call `transform.readInputAsString`, but I guess you are saying that code_transformers (and the analyzer etc. when used from there) will obey that discipline, such that there couldn't exist any dependencies that the `transform` hasn't seen. I didn't know that such a guarantee could be assumed.

**Comment by jakemac53** [comment]
Yes while you aren't directly calling those apis the code_transformers package is :)

**Comment by eernstg** [comment]
This means that an aggregate transform will provide information to `pub` about the global dependency pattern in a very coarse-grained manner: These k entry points depend, collectively, on those k+m assets.

This would then be the reason why it is better to have a more fine-grained setup: Entry point number j depends on a specific set of n_j assets. The n_j, j=1..k would be rather small, so we would know that entry point j doesn't have to be re-transformed until one of those n_j assets have been modified.

This brings us back to a very old discussion: Wouldn't we waste a lot of time resolving the same files over and over, if we get many invocations of apply just covering a single entry point?

**Comment by zoechi** [comment]
@jakemac53 
> Ah so it would be a pubspec level configuration in the users package, not something that is exposed to the transformer itself?

Yup, this is how I imagine it.

**Comment by jakemac53** [comment]
> This means that an aggregate transform will provide information to pub about the global dependency pattern in a very coarse-grained manner: These k entry points depend, collectively, on those k+m assets.
>
> This would then be the reason why it is better to have a more fine-grained setup: Entry point number j depends on a specific set of n_j assets. The n_j, j=1..k would be rather small, so we would know that entry point j doesn't have to be re-transformed until one of those n_j assets have been modified.

Yep

> This brings us back to a very old discussion: Wouldn't we waste a lot of time resolving the same files over and over, if we get many invocations of apply just covering a single entry point?

Only entry points are pimary assets, so apply is only invoked once for each entry point. All the entry points still share the same `Resolvers` object as well so they do share the analysis context.

**Comment by eernstg** [comment]
Yes, only entry points are primary assets, but we have `Resolvers resolvers = new Resolvers(dartSdkDirectory);` in `apply` so we get a new one for each invocation of `apply`. Just changed that---this probably resolves the reflectable issue https://github.com/dart-lang/reflectable/issues/32 and may also help here.

**Comment by jakemac53** [comment]
@zoechi is this still an issue?

**Comment by zoechi** [comment]
Works fine now :smiley:
