### ISSUE TITLE
fire doesn't populate CustomEvent.detail for non-core Dart Objects

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/polymer-dart#617]
Passing a plain Dart class results in null.  Passing a class mixing in JsProxy results in an empty Map. Passing Core objects like maps and ints work. Looking at the code I suspect the JsProxy version should work.  Not sure if a plain Dart class should work or not.  If it shouldn't then an error should be thrown.

**Comment by jakemac53** [comment]
How are you listening for the events? Custom events in general are a bit wonky in the interop world, try calling `convertToDart(event)` and then accessing the detail. That gives you a wrapper object around the event (which still implements CustomEvent) and deals with most of the nastiness. Otherwise the behavior is different between dart2js and dartium as well. This will automatically happen for event handlers which are set up by polymer (via template bindings for instance), but if you are manually setting up event listeners you have to do it on your own.

**Comment by ErikGrimes** [comment]
I added the listener via element.on['event-name'] as part of a test.  Using convertToDart on the event did the trick.

Should event handlers setup by Polymer convert JavaScript objects to Dart recursively?  I set one up and it converted the top level detail object into a map, but the values themselves are still JsObjects.

**Comment by jakemac53** [comment]
It should do this for JsObjects whos constructor is Object and whose prototype is Object.prototype, or for JsObjects who are just proxies to Dart objects. Everything else is left alone today.

**Comment by ErikGrimes** [comment]
Gotcha. This appears to be working as intended. I'm closing this issue.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/polymer-dart/issues/586 is another potential option here, if you felt like exploring something :)
