### ISSUE TITLE
Just broken link

### ISSUE THREAD

**Issue by rayk** [dart-lang/polymer-dart#709]
@kwalrath 
https://github.com/dart-lang/polymer-dart/wiki#structuring-your-app

Two links broken one to an I am and other to learning about imports. The pub structure one is working.

**Comment by jakemac53** [comment]
Hi Kathy, it looks like we were pointing at a graphic from the old site, do you know if that still exists?

**Comment by kwalrath** [comment]
Thanks for the report, @rayk. We've deleted that image, but I can give @jakemac53 a copy of it. (Perhaps it can go in this repo somewhere?)

**Comment by kwalrath** [comment]
As for the bad link, here's an archive: https://web.archive.org/web/20150703024342/https://www.dartlang.org/polymer/app-directories.html. We could point to that, I suppose.

However, we deleted that page because most of the information on it is no longer relevant, since we no longer use the transformer.

Non-web-specific pages that deal with package layout are at https://www.dartlang.org/guides/libraries/create-library-packages & https://www.dartlang.org/tools/pub/package-layout.

Perhaps we should write a web-specific version of how to structure your app, to live on webdev.dartlang.org. What do you think?

cc @Sfshaza

**Comment by jakemac53** [comment]
Ok, I fixed the broken image (just uploaded to imgur since that is the easiest and won't get fetched with a pub get).

I also linked to the archived page for now. That is actually a pretty good resource and we may want to revamp it and publish again elsewhere, at which point we can change the link.
